export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-slate-950 text-white">
      <div className="max-w-3xl mx-auto px-6 py-16">
        <h1 className="text-3xl font-bold mb-2">Terms of Service</h1>
        <p className="text-slate-500 text-sm mb-10">Last updated: June 2026</p>

        <div className="flex flex-col gap-8 text-slate-300 leading-relaxed">
          <section>
            <h2 className="text-lg font-semibold text-white mb-3">Acceptance</h2>
            <p>
              By using Resumio-AI you agree to these terms. If you do not agree, please do not use
              the service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">What Resumio-AI is</h2>
            <p>
              Resumio-AI is a job search tool that uses AI to match your resume against job listings
              and suggest portfolio projects. It is provided free of charge and on an as-is basis.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">Acceptable use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-5 flex flex-col gap-2 mt-2">
              <li>Use automated scripts or bots to make requests to the service</li>
              <li>Attempt to circumvent rate limits</li>
              <li>Upload files containing malicious code</li>
              <li>Use the service in any way that violates applicable law</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">AI-generated content</h2>
            <p>
              Job compatibility scores, match reasoning, and portfolio recommendations are
              generated by AI and may be inaccurate or incomplete. Do not rely solely on
              Resumio-AI&apos;s output when making career decisions. Always verify job listings and
              requirements directly with employers.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">Rate limits</h2>
            <p>
              To ensure fair access and control costs, requests are limited per IP address.
              Excessive use may result in temporary restrictions.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">No warranty</h2>
            <p>
              Resumio-AI is provided &quot;as is&quot; without warranty of any kind. We make no
              guarantees about uptime, accuracy of results, or fitness for any particular purpose.
              Job listings are sourced from third-party APIs and may be outdated or inaccurate.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">Limitation of liability</h2>
            <p>
              To the maximum extent permitted by law, Resumio-AI and its operators shall not be liable
              for any indirect, incidental, or consequential damages arising from your use of the
              service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">Changes</h2>
            <p>
              We may update these terms at any time. Continued use of the service after changes
              are posted constitutes acceptance of the new terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">Contact</h2>
            <p>
              Questions?{' '}
              <a href="mailto:jtsanders87@gmail.com" className="text-indigo-400 hover:underline">
                jtsanders87@gmail.com
              </a>
            </p>
          </section>
        </div>

        <a href="/" className="inline-block mt-12 text-sm text-slate-500 hover:text-white transition-colors">
          ← Back to Resumio-AI
        </a>
      </div>
    </div>
  );
}
